module.exports = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
        "*.{js,ts,jsx,tsx,mdx}",
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "#731017",
                    50: "#fef2f2",
                    100: "#fee2e2",
                    200: "#fecaca",
                    300: "#fca5a5",
                    400: "#f87171",
                    500: "#731017",
                    600: "#651014",
                    700: "#570e11",
                    800: "#4a0c0e",
                    900: "#3d0a0c",
                    950: "#2d0709",
                    foreground: "#ffffff",
                },
                secondary: {
                    DEFAULT: "#262626",
                    50: "#fafafa",
                    100: "#f5f5f5",
                    200: "#e5e5e5",
                    300: "#d4d4d4",
                    400: "#a3a3a3",
                    500: "#737373",
                    600: "#525252",
                    700: "#404040",
                    800: "#262626",
                    900: "#171717",
                    950: "#0a0a0a",
                    foreground: "#ffffff",
                },
                accent: {
                    DEFAULT: "#ffffff",
                    50: "#ffffff",
                    100: "#fefefe",
                    200: "#fdfdfd",
                    300: "#fcfcfc",
                    400: "#fbfbfb",
                    500: "#ffffff",
                    600: "#f5f5f5",
                    700: "#e5e5e5",
                    800: "#d4d4d4",
                    900: "#a3a3a3",
                    950: "#737373",
                    foreground: "#000000",
                },
                success: {
                    DEFAULT: "#16a34a",
                    50: "#f0fdf4",
                    100: "#dcfce7",
                    200: "#bbf7d0",
                    300: "#86efac",
                    400: "#4ade80",
                    500: "#22c55e",
                    600: "#16a34a",
                    700: "#15803d",
                    800: "#166534",
                    900: "#14532d",
                    950: "#052e16",
                    foreground: "#ffffff",
                },
                neutral: {
                    50: "#ffffff",
                    100: "#fafafa",
                    200: "#f5f5f5",
                    300: "#e5e5e5",
                    400: "#d4d4d4",
                    500: "#a3a3a3",
                    600: "#737373",
                    700: "#525252",
                    800: "#404040",
                    900: "#262626",
                    950: "#000000",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            animation: {
                "fade-in": "fadeIn 0.3s ease-out",
                "slide-up": "slideUp 0.3s ease-out",
                "slide-in-left": "slideInLeft 0.3s ease-out",
                "slide-in-right": "slideInRight 0.3s ease-out",
            },
            keyframes: {
                fadeIn: {
                    from: { opacity: "0" },
                    to: { opacity: "1" },
                },
                slideUp: {
                    from: { opacity: "0", transform: "translateY(20px)" },
                    to: { opacity: "1", transform: "translateY(0)" },
                },
                slideInLeft: {
                    from: { opacity: "0", transform: "translateX(-20px)" },
                    to: { opacity: "1", transform: "translateX(0)" },
                },
                slideInRight: {
                    from: { opacity: "0", transform: "translateX(20px)" },
                    to: { opacity: "1", transform: "translateX(0)" },
                },
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
